title = "affected book"
#baseURL = "https://affectedbook.com"
baseURL = "http://affectedbook.com.s3-website-ap-southeast-2.amazonaws.com"
tags = ["affected book", "design thinking", "companion"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = "UA-31178888-7"
disqusShortname = "affected"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies

[Params]
    tagline = "emotionally engaging customers in the digital age"
    queryline = "Find out what Johnny Depp, German porn and Burberry have in common."
    author = "Rob Dongas"
    description = "Companion website for Affected the book."
    logoSmall = "/images/affected-icon.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/affected-icon.png"
    twitter = ""
    linkedin = ""
    github = ""
    facebook = ""
    email = ""
    googleTagManger = ""
    copyright = true
    customCSS = false
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = false

[[menu.main]]
    name = "for whom"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "structure"
    url  = "/#structure"
    weight = 2
[[menu.main]]
    name = "authors"
    url  = "/#authors"
    weight = 3
[[menu.main]]
    name = "foxes"
    url  = "/#foxes"
    weight = 4
# [[menu.main]]
#     name = "Blog"
#     url  = "#blog"
#     weight = 3
# [[menu.main]]
#     name = "Contact"
#     url  = "#contact"
#     weight = 4
